//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter Recipe Title!")]
        public string RecipeTitle { get; set; }

        [Required(ErrorMessage = "Please Enter Recipe Author!")]
        public string Author { get; set; }

        [DataType(DataType.DateTime)]
        public System.DateTime PublishDate { get; set; }

        [Required(ErrorMessage = "Please Enter Recipe Content!")]
        public string Content { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
