//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter Reviewer Name!")]
        public string Reviewer { get; set; }

        [DataType(DataType.DateTime)]
        public System.DateTime PublishDate { get; set; }

        [Required(ErrorMessage = "Please Enter Review Content!")]
        public string Content { get; set; }

        public int RecipeId { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
